import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "code-editor",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/coding-svgrepo-com.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/icons/coding-svgrepo-com.svg" type="image/png" />
      </head>
      <body className="bg-black text-white">{children}</body>
    </html>
  );
}
